version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: veroDigit:v1
    restart: always
    build: .
    ports:
      - 9090:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      SPRING_PROFILES_ACTIVE: prod
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: veroDigit
      MYSQL_ROOT_PASSWORD: root
